FORMAT: 1A
HOST: http://serverlessdemo.docs.apiary.io/

# serverless-demo

Serverless-demo is a nodejs based, prototype, API boilerplate that will be used to create
serverless, AWS lambda-based, APIs in the future. The central API resource theme is 'items'.
When building a new API based on this prototype, replace the 'items' resource with the
resource name of your choice. This boilerplate will contain basic, example functionality
for all CRUD operations, and any supporting logic such as serialization, and MongoDB
integration, schema validation, CI/CD using Codehsip CI, unit testing with mocha and chai,
api endpoint testing using dredd and this API blueprint document, as well as documentation
using the apiary platform.

# Group Items
Items are what this api service is all about. They are a great representation of just about
anything, yet generic enough to serve as the perfect boilerplate example.
With this service, you can create, update, delete, read one, or even read many items.
See the examples below for information on how to do each action on this resource.

## Item Collection [/items]

### List All Items [GET]

Retrieve all items for this resource.

+ Response 200 (application/vnd.api+json)

        {
            "data": [
                {
                    "type": "items",
                    "id": "1",
                    "attributes": {
                        "field-1": "foo",
                        "field-2": [
                            "fiz",
                            "buz"
                        ],
                        "field-3": {
                            "key-1": "value-1",
                            "key-2": "value-2"
                        }
                    }
                },
                {
                    "type": "items",
                    "id": "2",
                    "attributes": {
                        "field-1": "bar",
                        "field-2": [
                            "cat",
                            "dog"
                        ],
                        "field-3": {
                            "key-1": "value-3",
                            "key-2": "value-4"
                        }
                    }
                }
            ]
        }

### Create a Single Item [POST]

You may create a single item using this resource.

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "field-1": "foo",
                    "field-2": [
                        "fiz",
                        "buz"
                    ],
                    "field-3": {
                        "key-1": "value-1",
                        "key-2": "value-2"
                    }
                },
                "type": "items"
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /items/3

    + Body

            {
                "data": {
                    "type": "items",
                    "id": "3",
                    "attributes": {
                        "field-1": "foo",
                        "field-2": [
                            "fiz",
                            "buz"
                        ],
                        "field-3": {
                            "key-1": "value-1",
                            "key-2": "value-2"
                        }
                    }
                }
            }
            
## Item [/items/{item_id}]

### Get a single Item [GET]
            