FORMAT: 1A
HOST: http://serverlessdemo.docs.apiary.io/

# serverless-demo

Serverless-demo is a nodejs based, prototype, API boilerplate that will be used to create
serverless, AWS lambda-based, APIs in the future. The central API resource theme is 'items'.
When building a new API based on this prototype, replace the 'items' resource with the
resource name of your choice. This boilerplate will contain basic, example functionality
for all CRUD operations, and any supporting logic such as serialization, and MongoDB
integration, schema validation, CI/CD using Codehsip CI, unit testing with mocha and chai,
api endpoint testing using dredd and this API blueprint document, as well as documentation
using the apiary platform.

# Items Collection [/items]

## List All Items [GET]

Retrieve all items for this resource.

+ Response 200 (application/vnd.api+json)

        {
            "data": [
                {
                    "type": "items",
                    "id": "1",
                    "attributes": {
                        "field-1": "foo",
                        "field-2": [
                            "fiz",
                            "buz"
                        ],
                        "field-3": {
                            "key-1": "value-1",
                            "key-2": "value-2"
                        }
                    }
                },
                {
                    "type": "items",
                    "id": "2",
                    "attributes": {
                        "field-1": "bar",
                        "field-2": [
                            "cat",
                            "dog"
                        ],
                        "field-3": {
                            "key-1": "value-3",
                            "key-2": "value-4"
                        }
                    }
                }
            ]
        }

## Create a Single Item [POST]

You may create a single item using this resource.

+ Request (application/vnd.api+json)

        {
            "data": {
                "type": "item",
                "attributes": {
                    "item-foo": "fiz",
                    "item-bar": 1,
                    "item-sub-object": {
                        "sub-field": "test"
                    }
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Body

            {
                "data": {
                    "type": "item",
                    "id": "3",
                    "attributes": {
                        "item-foo": "fiz",
                        "item-bar": 1,
                        "item-sub-object": {
                            "sub-field": "test"
                        }
                    }
                }
            }
            