FORMAT: 1A
HOST: http://serverlessdemo.docs.apiary.io/

# serverless-demo

Serverless-demo is a prototype API boilerplate that will be used to create lambda APIs in the future.
The central API resource theme is 'items'. When building a new API based on this prototype, replace the 'items' resource with the resource name of your choice.

## Items Collection [/items]

### List All Items [GET]

+ Response 200 (application/vnd.api+json)

        {
            "data": [
                {
                    "attributes": {
                        "field-1": "foo",
                        "field-2": [
                            "fiz",
                            "buz
                        ],
                        "field-3": {
                            "key-1": "value-1",
                            "key-2": "value-2"
                        }
                    },
                    "id": "1",
                    "type": "item"
                },
                {
                    "attributes": {
                        "field-1": "bar",
                        "field-2": [
                            "cat",
                            "dog
                        ],
                        "field-3": {
                            "key-1": "value-3",
                            "key-2": "value-4"
                        }
                    },
                    "id": "2",
                    "type": "item"
                }
            ]
        }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }