service: serverless-demo

provider:
  name: aws
  runtime: nodejs8.10 # AWS Lambda nodejs runtime.
  profile: qa # AWS credentials profile. Found in ~/.aws/credentials.
  stage: qa
  region: us-west-2

package:
 include:
   - handlers/**
   - models/**
   - utils/**
   - .env
   - node_modules/**
 exclude:
   - ./**

functions:
  error405: # Catch all error handler for "Method not Allowed" erros.
    handler: handlers/errors.error405
    events:
      - http:
          path: /things
          method: any
      - http:
          path: /things/{id}
          method: any
          
  error404: # Catch all error handling for invalid resources.
    handler: handlers/errors.error404
    events:
      - http:
          path: /
          method: any
      - http:
          path: /things/{id}/{proxy+}
          method: any
  
  create:
    handler: handlers/create.create
    events:
      - http:
          path: /items
          method: post

  readMany:
    handler: handlers/readMany.read
    events:
      - http:
          path: /items
          method: get

  readOne:
    handler: handlers/readOne.read
    events:
      - http:
          path: /things/{id}
          method: get
  
  update:
    handler: handlers/update.update
    events:
      - http:
          path: /things/{id}
          method: patch
  
  delete:
    handler: handlers/delete.delete
    events:
      - http:
          path: /things/{id}
          method: delete

plugins:
- serverless-offline
