service: sls-sites-api-demo

provider:
  name: aws
  runtime: nodejs6.10
  profile: qa # AWS credentials profile. Found in ~/.aws/credentials.
  stage: qa
  region: us-west-2

package:
 include:
   - handler.js
 exclude:
   - ./**

functions:
  readSites:
    handler: handler.readSites
    events:
      - http:
          path: /sites
          method: get

  readSite:
    handler: handler.readSite
    events:
      - http:
          path: /sites/{subdomain}
          method: get
  
  createSite:
    handler: handler.createSite
    events:
      - http:
          path: /sites/{subdomain}
          method: post
  
  updateSite:
    handler: handler.updateSite
    events:
      - http:
          path: /sites/{subdomain}
          method: patch
  
  deleteSite:
    handler: handler.deleteSite
    events:
      - http:
          path: /sites/{subdomain}
          method: delete