service: serverless-demo

provider:
  name: aws
  runtime: nodejs8.10 # AWS Lambda nodejs runtime.
  profile: qa # AWS credentials profile. Found in ~/.aws/credentials.
  stage: qa
  region: us-west-2

package:
 include:
   - handlers/**
   - models/**
   - utils/**
   - .env
   - node_modules/**
 exclude:
   - ./**

functions:
  error405: # Catch all error handler for "Method not Allowed" erros.
    handler: sites/handlers/errors.error405
    events:
      - http:
          path: /sites
          method: any
      - http:
          path: /sites/{subdomain}
          method: any
          
  error404: # Catch all error handling for invalid resources.
    handler: sites/handlers/errors.error404
    events:
      - http:
          path: /
          method: any
      - http:
          path: /sites/{subdomain}/{proxy+}
          method: any
  
  create:
    handler: sites/handlers/create.create
    events:
      - http:
          path: /sites
          method: post

  readMany:
    handler: sites/handlers/readMany.read
    events:
      - http:
          path: /sites
          method: get

  readOne:
    handler: sites/handlers/readOne.read
    events:
      - http:
          path: /sites/{subdomain}
          method: get
  
  update:
    handler: sites/handlers/update.update
    events:
      - http:
          path: /sites/{subdomain}
          method: patch
  
  delete:
    handler: sites/handlers/delete.delete
    events:
      - http:
          path: /sites/{subdomain}
          method: delete

plugins:
- serverless-offline
